### ISSUE TITLE
ios: advanced -> restart device doesn't work

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/stf#275]
open iOS device, activate Advanced and press `Restart Device`
-> nothing happens

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/stf/pull/276
so far until devices not paired you have to be near the mCloud to trust the connection after restart

**Comment by dhreben** [comment]
Fixed:
Verified 5 times

**Comment by dhreben** [comment]
Reopened.


**Steps:**

1. Open iOS device
2. Click Advanced and press Restart Device

**Actual result:** Nothing happens after click restart device button

**Comment by vdelendik** [comment]
@dhreben let's retest. make sure to use iOS devices connected via Linux. If issue still exists for iOS simulators or connected via Mac then submit new ticket
