### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined  after upload ipa file into STF

### ISSUE THREAD

**Issue by dhreben** [zebrunner/stf#401]
**Steps:**

1.Open STF
2.Upload  ipa file

 **Actual result:** TypeError: Cannot read property 'includes' of undefined  after upload ipa file into STF

**See screenshot:**

<img width="1126" alt="Screenshot 2022-04-19 at 15 57 48" src="https://user-images.githubusercontent.com/50950954/164019335-7c8cc6f6-b5d3-4b5b-bb7d-c233399b45fe.png">

**Logs:**

```
ff64a0/74c354e0ff33ad8fd77863571e9f8327","path":"/s/apk/7790d540-eda6-495c-910f-f367e9ff64a0/74c354e0ff33ad8fd77863571e9f8327","href":"https://demo.zebrunner.farm:443/s/apk/7790d540-eda6-495c-910f-f3.......................7863571e9f8327"},"method":"GET","headers":{"host":"demo.zebrunner.farm"}}
2022-04-19T13:22:06.232Z INF/device:plugins:install 8 [b09fa26acc4c.................243f862b5] source.uri.href: https://demo.zebrunner.farm:443/s/apk/7790d540-eda6-495c-910f-f367e9ff64a0/74c354e0ff33ad8fd77863571e9f8327
2022-04-19T13:22:06.232Z INF/device:plugins:install 8 [b09fa...............f862b5] mkdir "/tmp/6be459a1-605a-489e-8877-3f014c3eb0d0"
2022-04-19T13:22:07.326Z INF/device:plugins:install 8 [b09fa26acc4c.....................62b5] Download Completed
/opt/lib/units/ios-device/plugins/install.js:142
                 isSimulator = manifest.DTPlatformName.includes("simulator")
TypeError: Cannot read property 'includes' of undefined
    at WriteStream.file.on (/opt/lib/units/ios-device/plugins/install.js:142:56)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:613:14)
    at afterWrite (_stream_writable.js:464:3)
    at onwrite (_stream_writable.js:454:7)
    at fs.write (fs.js:2194:5)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:685:5)
Exit status: 1

```
**Note**:  Ipa.file is attached into thread Slack

**Comment by vdelendik** [comment]
inside provided production ipa Info.plist is already xml file so extra converting not required...

**Comment by vdelendik** [comment]
fixed. it should display error message starting from now. in device container logs or in stf service log on mac real cause should be displayed, for example:
```
{"err":"your app is not properly signed for this device, check your codesigning and provisioningprofile. original error: 'ApplicationVerificationFailed' errorDescription:'Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ig2ten/extracted/Payload/FoxApp.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)'","level":"fatal","msg":"failed writing","time":"2022-04-20T11:43:56Z"}
```

**Comment by dhreben** [comment]
Fixed

**Comment by vdelendik** [comment]
issue is still repro on the ipa where Info.plist is xml file already

**Comment by vdelendik** [comment]
done, 2.1 stf should be published as 2.1.1, also 2.1 tag should point onto the new version
